apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T13:50:10Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "493"
  uid: 2e6f6c0f-17c4-4ce5-8350-88a2027c8590
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.1.34
  clusterIPs:
  - 10.96.1.34
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30321
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
