apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T11:39:05Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "19401"
  uid: 04c25ef6-cb3c-4e23-8d8e-9b4a38946979
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.141.26
  clusterIPs:
  - 10.100.141.26
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30138
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
